const GAMESTATUS = {};
GAMESTATUS[GAMESTATUS.BETTING = 1] = 'BETTING';
GAMESTATUS[GAMESTATUS.RESULTING = 2] = 'RESULTING';
GAMESTATUS[GAMESTATUS.SHUFFLING = 11] = 'SHUFFLING';
GAMESTATUS[GAMESTATUS.WAITING = 0] = 'WAITING';

GAMESTATUS_READABLE = {
    BETTING: '可以下注',
    RESULTING: '正在开牌',
    SHUFFLING: '正在洗牌',
    WAITING: '等待开局',
}

module.exports = {
    GAMESTATUS,
    GAMESTATUS_READABLE,
}