const PLAYTYPES = {};
PLAYTYPES[PLAYTYPES.PLAYTYPE_BANKER = 1] = 'PLAYTYPE_BANKER'
PLAYTYPES[PLAYTYPES.PLAYTYPE_PLAYER = 2] = 'PLAYTYPE_PLAYER'
PLAYTYPES[PLAYTYPES.PLAYTYPE_TIE = 3] = 'PLAYTYPE_TIE'
PLAYTYPES[PLAYTYPES.PLAYTYPE_BANKER_PAIR = 4] = 'PLAYTYPE_BANKER_PAIR'
PLAYTYPES[PLAYTYPES.PLAYTYPE_PLAYER_PAIR = 5] = 'PLAYTYPE_PLAYER_PAIR'
PLAYTYPES[PLAYTYPES.PLAYTYPE_BIG = 6] = 'PLAYTYPE_BIG'
PLAYTYPES[PLAYTYPES.PLAYTYPE_SMALL = 7] = 'PLAYTYPE_SMALL'
PLAYTYPES[PLAYTYPES.PLAYTYPE_BANKER_DRAGON_BONUS = 12] = 'PLAYTYPE_BANKER_DRAGON_BONUS'
PLAYTYPES[PLAYTYPES.PLAYTYPE_PLAYER_DRAGON_BONUS = 13] = 'PLAYTYPE_PLAYER_DRAGON_BONUS'
PLAYTYPES[PLAYTYPES.PLAYTYPE_SUPER_SIX = 14] = 'PLAYTYPE_SUPER_SIX'
PLAYTYPES[PLAYTYPES.PLAYTYPE_ANY_PAIR = 15] = 'PLAYTYPE_ANY_PAIR'
PLAYTYPES[PLAYTYPES.PLAYTYPE_PERFECT_PAIR = 16] = 'PLAYTYPE_PERFECT_PAIR'

const PLAYTYPES_READABLE = {
    PLAYTYPE_BANKER: '庄',
    PLAYTYPE_PLAYER: '闲',
    PLAYTYPE_TIE: '和',
    PLAYTYPE_BANKER_PAIR: '庄对',
    PLAYTYPE_PLAYER_PAIR: '闲对',
    PLAYTYPE_BIG: '大',
    PLAYTYPE_SMALL: '小',
    PLAYTYPE_BANKER_DRAGON_BONUS: '庄龙宝',
    PLAYTYPE_PLAYER_DRAGON_BONUS: '闲龙宝',
    PLAYTYPE_SUPER_SIX: '666',
    PLAYTYPE_ANY_PAIR: '任意对子',
    PLAYTYPE_PERFECT_PAIR: '完美对子',
}

module.exports = {
    PLAYTYPES,
    PLAYTYPES_READABLE,
}